<?php
declare(strict_types=1);

namespace Tests\Postgres;

use Fyre\DB\ConnectionManager;
use Fyre\DB\Handlers\Postgres\PostgresConnection;
use Fyre\Entity\EntityLocator;
use Fyre\ORM\BehaviorRegistry;
use Fyre\ORM\ModelRegistry;

use function getenv;

trait PostgresConnectionTrait
{
    public static function setUpBeforeClass(): void
    {
        ConnectionManager::clear();
        ConnectionManager::setConfig('default', [
            'className' => PostgresConnection::class,
            'host' => getenv('POSTGRES_HOST'),
            'username' => getenv('POSTGRES_USERNAME'),
            'password' => getenv('POSTGRES_PASSWORD'),
            'database' => getenv('POSTGRES_DATABASE'),
            'port' => getenv('POSTGRES_PORT'),
            'charset' => 'utf8',
            'persist' => false,
        ]);

        $connection = ConnectionManager::use();

        $connection->query('DROP TABLE IF EXISTS contains');
        $connection->query('DROP TABLE IF EXISTS items');
        $connection->query('DROP TABLE IF EXISTS others');
        $connection->query('DROP TABLE IF EXISTS timestamps');
        $connection->query('DROP TABLE IF EXISTS users');
        $connection->query('DROP TABLE IF EXISTS addresses');
        $connection->query('DROP TABLE IF EXISTS posts');
        $connection->query('DROP TABLE IF EXISTS comments');
        $connection->query('DROP TABLE IF EXISTS tags');
        $connection->query('DROP TABLE IF EXISTS posts_tags');

        $connection->query(<<<'EOT'
            CREATE TABLE items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE contains (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                item_id INTEGER NOT NULL,
                contained_item_id INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE others (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE timestamps (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                created TIMESTAMP NOT NULL,
                modified TIMESTAMP NOT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE addresses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NOT NULL,
                address_1 VARCHAR(255) NULL DEFAULT NULL,
                address_2 VARCHAR(255) NULL DEFAULT NULL,
                suburb VARCHAR(255) NULL DEFAULT NULL,
                state VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE posts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NULL DEFAULT NULL,
                title VARCHAR(255) NULL DEFAULT NULL,
                content TEXT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE comments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NULL DEFAULT NULL,
                post_id INTEGER NULL DEFAULT NULL,
                content TEXT NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE tags (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                tag VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        EOT);

        $connection->query(<<<'EOT'
            CREATE TABLE posts_tags (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                post_id INTEGER NOT NULL,
                tag_id INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        EOT);
    }

    public static function tearDownAfterClass(): void
    {
        $connection = ConnectionManager::use();
        $connection->query('DROP TABLE IF EXISTS contains');
        $connection->query('DROP TABLE IF EXISTS items');
        $connection->query('DROP TABLE IF EXISTS others');
        $connection->query('DROP TABLE IF EXISTS timestamps');
        $connection->query('DROP TABLE IF EXISTS users');
        $connection->query('DROP TABLE IF EXISTS addresses');
        $connection->query('DROP TABLE IF EXISTS posts');
        $connection->query('DROP TABLE IF EXISTS comments');
        $connection->query('DROP TABLE IF EXISTS tags');
        $connection->query('DROP TABLE IF EXISTS posts_tags');
    }

    protected function setUp(): void
    {
        BehaviorRegistry::clear();
        BehaviorRegistry::addNamespace('Tests\Mock\Behaviors');

        EntityLocator::clear();
        EntityLocator::addNamespace('Tests\Mock\Entity');

        ModelRegistry::clear();
        ModelRegistry::addNamespace('Tests\Mock\Model');
    }

    protected function tearDown(): void
    {
        $connection = ConnectionManager::use();
        $connection->query('TRUNCATE items RESTART IDENTITY');
        $connection->query('TRUNCATE others RESTART IDENTITY');
        $connection->query('TRUNCATE timestamps RESTART IDENTITY');
        $connection->query('TRUNCATE users RESTART IDENTITY');
        $connection->query('TRUNCATE addresses RESTART IDENTITY');
        $connection->query('TRUNCATE posts RESTART IDENTITY');
        $connection->query('TRUNCATE comments RESTART IDENTITY');
        $connection->query('TRUNCATE tags RESTART IDENTITY');
        $connection->query('TRUNCATE posts_tags RESTART IDENTITY');
    }
}
